<a href="https://colab.research.google.com/github/Sergiopira95/Python_Learn/blob/main/101_numpy_exercises.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import numpy as np

In [ ]:
print(np.__version__)

1.26.4


In [ ]:
arr = np.arange(0,10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
true_array = np.full(shape=(3,3), fill_value=True, dtype=bool)
true_array

array([[ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]])

In [ ]:
arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
arr[arr % 2 == 1]

array([1, 3, 5, 7, 9])

In [ ]:
arr[arr % 2 == 1] = -1
arr

array([ 0, -1,  2, -1,  4, -1,  6, -1,  8, -1])

In [ ]:
arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
out = arr.copy()
out[arr % 2 == 1] = -1
print(arr)
out

[0 1 2 3 4 5 6 7 8 9]


array([ 0, -1,  2, -1,  4, -1,  6, -1,  8, -1])

In [ ]:
#6. How to replace items that satisfy a condition without affecting the original array?

arr = np.arange(10)
out = np.where(arr % 2 == 1, -1, arr)
print(arr)
out

[0 1 2 3 4 5 6 7 8 9]


array([ 0, -1,  2, -1,  4, -1,  6, -1,  8, -1])

In [ ]:
#7. How to reshape an array?
arr = np.arange(0,9)
print(arr)
print(np.shape(arr))
reshaped_arr = np.reshape(arr, (3,3))
print(reshaped_arr)
print(np.shape(reshaped_arr))

#Other Solution
arr = np.arange(10)
arr.reshape(2, -1)  # Setting to -1 automatically decides the number of cols

[0 1 2 3 4 5 6 7 8]
(9,)
[[0 1 2]
 [3 4 5]
 [6 7 8]]
(3, 3)


array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [ ]:
#8. How to stack two arrays vertically?
a = np.arange(10).reshape(2,-1)
b = np.repeat(1, 10).reshape(2,-1)
# Method 1:
np.concatenate([a, b], axis=0)

# Method 2:
np.vstack([a, b])

# Method 3:
np.r_[a, b]

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [ ]:
#9. How to stack two arrays horizontally?
a = np.arange(10).reshape(2,-1)

b = np.repeat(1, 10).reshape(2,-1)

# Method 1:
np.concatenate([a, b], axis=1)

# Method 2:
np.hstack([a, b])

# Method 3:
np.c_[a, b]

array([[0, 1, 2, 3, 4, 1, 1, 1, 1, 1],
       [5, 6, 7, 8, 9, 1, 1, 1, 1, 1]])

10. How to generate custom sequences in numpy without hardcoding?
Difficulty Level: L2

Q. Create the following pattern without hardcoding. Use only numpy functions and the below input array a.

Desired Output:

array([1, 1, 1, 2, 2, 2, 3, 3, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3])

In [ ]:
# My solution

a = np.array([1,2,3])
a = np.repeat(a, 3)
for _ in np.arange(3):
  a = np.hstack([a, [1,2,3]])
a


array([1, 1, 1, 2, 2, 2, 3, 3, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3])

In [ ]:
# Alternative solution
a = np.array([1,2,3])
np.r_[np.repeat(a, 3), np.tile(a, 3)]

array([1, 1, 1, 2, 2, 2, 3, 3, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3])

#11. How to get the common items between two python numpy arrays?
Difficulty Level: L2

Q. Get the common items between a and b

##Input:

a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])

##Desired Output:

array([2, 4])

In [ ]:
a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])

np.intersect1d(a, b)

array([2, 4])

#12. How to remove from one array those items that exist in another?
Difficulty Level: L2

Q. From array a remove all items present in array b

##Input:

a = np.array([1,2,3,4,5])
b = np.array([5,6,7,8,9])

##Desired Output:

array([1,2,3,4])

In [ ]:
a = np.array([1,2,3,4,5])
b = np.array([5,6,7,8,9])

# From 'a' remove all of 'b'

np.setdiff1d(a,b)

array([1, 2, 3, 4])

#13. How to get the positions where elements of two arrays match?
Difficulty Level: L2

Q. Get the positions where elements of a and b match

##Input:

a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])

##Desired Output:

array([1, 3, 5, 7])

In [ ]:
a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])

#If only the condition is provided,
#numpy.where() returns the indices of elements that meet the condition.

np.where(a == b)

(array([1, 3, 5, 7]),)

#14. How to extract all numbers between a given range from a numpy array?
Difficulty Level: L2

Q. Get all items between 5 and 10 from a.

##Input:

a = np.array([2, 6, 1, 9, 10, 3, 27])

##Desired Output:

(array([6, 9, 10]),)

In [ ]:
a = np.array([2, 6, 1, 9, 10, 3, 27])

# Method 1
index = np.where((a >= 5) & (a <= 10))
a[index]

# Method 2:
index = np.where(np.logical_and(a>=5, a<=10))
a[index]


# Method 3: (thanks loganzk!)
a[(a >= 5) & (a <= 10)]

array([ 6,  9, 10])

#15. How to make a python function that handles scalars to work on numpy arrays?
Difficulty Level: L2

Q. Convert the function maxx that works on two scalars, to work on two arrays.

##Input:

def maxx(x, y):
    """Get the maximum of two items"""
    if x >= y:
        return x
    else:
        return y

maxx(1, 5)
#> 5
##Desired Output:

a = np.array([5, 7, 9, 8, 6, 4, 5])
b = np.array([6, 3, 4, 8, 9, 7, 1])
pair_max(a, b)
#> array([ 6.,  7.,  9.,  8.,  9.,  7.,  5.])

In [ ]:
# My solution
def maxx(x, y):
  """Get the maximum of two items"""
  if x >= y:
    return x
  else:
    return y

a = np.array([5, 7, 9, 8, 6, 4, 5])
b = np.array([6, 3, 4, 8, 9, 7, 1,5])

if a.shape != b.shape:
    print('Array dimensions should be the  same')
else:
    pair_max = np.vectorize(maxx, otypes=[int])
    pair_max(a, b)


Array dimensions should be the  same


##16. How to swap two columns in a 2d numpy array?
Difficulty Level: L2

Q. Swap columns 1 and 2 in the array arr.

arr = np.arange(9).reshape(3,3)

arr

In [6]:
arr = np.arange(9).reshape(3,3)
arr


array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [7]:
# My solution
arr1 = arr.copy()
arr[:,0] = arr[:,1]
arr[:,1] = arr1[:,0]
arr

array([[1, 0, 2],
       [4, 3, 5],
       [7, 6, 8]])

In [8]:
# Alternative solution
arr[:, [1,0,2]]

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [9]:
# Another solution suplied by Gemini
arr = np.arange(9).reshape(3,3)
arr[:,[1, 0]] = arr[:,[0, 1]] # Swaps the first and second column of the entire array
arr

array([[1, 0, 2],
       [4, 3, 5],
       [7, 6, 8]])

## 17. How to swap two rows in a 2d numpy array?
Difficulty Level: L2

Q. Swap rows 1 and 2 in the array arr:

arr = np.arange(9).reshape(3,3)
arr

In [4]:
# My solution
arr = np.arange(9).reshape(3,3)
arr[[0,1],:] = arr[[1,0],:]
arr

array([[3, 4, 5],
       [0, 1, 2],
       [6, 7, 8]])